token:
  expiration_time: 86400000
#   # secret: user_token_native_application
  secret: '{cipher}AQAfHYPo0GND9YYmST3TTLlECpWA2qIKcwlNfHwtQh6bSf5r8BBm3BVtBkOrMZ4+sgiHPe9AxELuNvOfb1vd1/k2teoU1U0SPeegJT35FV6T4qVO9kqvvOWKQeaQb7xsBOMoCHHRk+tepcKmA3hYADhsuuzAqz7nIfwxEMEeEmgoov1VbPKiJZmftJg6dFktmvOTYQuJJq9psb9Xa26351KXtoCpnjPSzcYI4qJQ6aagGTiwertprD/y8fEs2WKQSChzXSA16aSmxh6R1PSoDjP/8RSK5oSvf420Uf6nBrSZa1l5acfO7J1je7xLOl6dc579oLm4QneWmOuO8IMXafBwjqFUOn4t7u7R4pe2/s5ZMcjJUWIz7PP31U+zd8TtWanYHmlEVs11C1x/8NWWtFMJ'

gateway:
  ip: 192.168.0.13
